// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2t6gMFMzBuyFgn6ObXshgpb2WEpNCLlk',
    appId: '1:687793669558:web:3962116f7f1174b7992d17',
    messagingSenderId: '687793669558',
    projectId: 'mimari-atlasai',
    authDomain: 'mimari-atlasai.firebaseapp.com',
    storageBucket: 'mimari-atlasai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDPifL59GDmRHFLTVPk5nDZTn9Ral8M4',
    appId: '1:687793669558:android:ed52c715b2fb8850992d17',
    messagingSenderId: '687793669558',
    projectId: 'mimari-atlasai',
    storageBucket: 'mimari-atlasai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyx8oVtOSAjkHyD5lBdXBI1h-pSwslAM',
    appId: '1:687793669558:ios:f802d8eedb1ebcdd992d17',
    messagingSenderId: '687793669558',
    projectId: 'mimari-atlasai',
    storageBucket: 'mimari-atlasai.firebasestorage.app',
    iosBundleId: 'com.example.mimariAtlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpyx8oVtOSAjkHyD5lBdXBI1h-pSwslAM',
    appId: '1:687793669558:ios:f802d8eedb1ebcdd992d17',
    messagingSenderId: '687793669558',
    projectId: 'mimari-atlasai',
    storageBucket: 'mimari-atlasai.firebasestorage.app',
    iosBundleId: 'com.example.mimariAtlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2t6gMFMzBuyFgn6ObXshgpb2WEpNCLlk',
    appId: '1:687793669558:web:78fb345da1d3edc0992d17',
    messagingSenderId: '687793669558',
    projectId: 'mimari-atlasai',
    authDomain: 'mimari-atlasai.firebaseapp.com',
    storageBucket: 'mimari-atlasai.firebasestorage.app',
  );
}
